// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJSKyOxqBUVhx2El01uidMn3iJ5uteIU',
    appId: '1:25547990004:web:aa6f26cdd59f2afb0f0fa1',
    messagingSenderId: '25547990004',
    projectId: 'instagram-clone-edb2c',
    authDomain: 'instagram-clone-edb2c.firebaseapp.com',
    storageBucket: 'instagram-clone-edb2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNN2U03Pemf_RVHcccuQXSBr69KQSFvw',
    appId: '1:25547990004:android:ff7d4c04ac6b29ce0f0fa1',
    messagingSenderId: '25547990004',
    projectId: 'instagram-clone-edb2c',
    storageBucket: 'instagram-clone-edb2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-kC_X8WbtUFdTttQMX-Hu96dWV8qbaVk',
    appId: '1:25547990004:ios:8a14d900ca0ed0990f0fa1',
    messagingSenderId: '25547990004',
    projectId: 'instagram-clone-edb2c',
    storageBucket: 'instagram-clone-edb2c.appspot.com',
    iosClientId: '25547990004-st8djqp5rbot9q00506vda2q5j7as8ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-kC_X8WbtUFdTttQMX-Hu96dWV8qbaVk',
    appId: '1:25547990004:ios:8a14d900ca0ed0990f0fa1',
    messagingSenderId: '25547990004',
    projectId: 'instagram-clone-edb2c',
    storageBucket: 'instagram-clone-edb2c.appspot.com',
    iosClientId: '25547990004-st8djqp5rbot9q00506vda2q5j7as8ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
